import { CurrencyCode } from './code.enum';
import { CurrencyVariants } from './currency';
import { Currency } from './currency.enum';

export function getCurrencySymbol(currency: CurrencyVariants): string | null {
  switch (currency) {
    case Currency.Ruble:
    case CurrencyCode.Ruble:
      return `₽`;
    case Currency.Dollar:
    case CurrencyCode.Dollar:
    case Currency.MexicanPeso:
    case CurrencyCode.MexicanPeso:
      return `$`;
    case Currency.SingaporeDollar:
    case CurrencyCode.SingaporeDollar:
      return `S$`;
    case Currency.AustralianDollar:
    case CurrencyCode.AustralianDollar:
      return `A$`;
    case Currency.HongKongDollar:
    case CurrencyCode.HongKongDollar:
      return `HK$`;
    case Currency.CanadianDollar:
    case CurrencyCode.CanadianDollar:
      return `C$`;
    case Currency.Euro:
    case CurrencyCode.Euro:
      return `€`;
    case Currency.Pound:
    case CurrencyCode.Pound:
      return `£`;
    case Currency.Baht:
    case CurrencyCode.Baht:
      return `฿`;
    case Currency.TurkishLira:
    case CurrencyCode.TurkishLira:
      return `₺`;
    case Currency.YuanRenminbi:
    case CurrencyCode.YuanRenminbi:
      return `CN¥`;
    case Currency.Yen:
    case CurrencyCode.Yen:
      return `¥`;
    case Currency.IsraeliShekel:
    case CurrencyCode.IsraeliShekel:
      return `₪`;
    case Currency.IndianRupee:
    case CurrencyCode.IndianRupee:
      return `₹`;
    case Currency.SwissFranc:
    case CurrencyCode.SwissFranc:
      return `₣`;
    case Currency.ArmenianDram:
    case CurrencyCode.ArmenianDram:
      return `֏`;
    case Currency.Won:
    case CurrencyCode.Won:
      return `₩`;
    case Currency.Tenge:
    case CurrencyCode.Tenge:
      return `₸`;
    case Currency.Hryvnia:
    case CurrencyCode.Hryvnia:
      return `₴`;
    case Currency.UzbekSum:
    case CurrencyCode.UzbekSum:
      return `So'm`;
    case Currency.KyrgyzstanSom:
    case CurrencyCode.KyrgyzstanSom:
      return `c`;
    case Currency.Dirham:
    case CurrencyCode.Dirham:
      return `Dh`;
    case Currency.TajikistaniSomoni:
    case CurrencyCode.TajikistaniSomoni:
      return `SM`;
    case Currency.MalaysianRinggit:
    case CurrencyCode.MalaysianRinggit:
      return `RM`;
    case Currency.BelarusianRuble:
    case CurrencyCode.BelarusianRuble:
      return `Rbl`;
    case Currency.GeorgianLari:
    case CurrencyCode.GeorgianLari:
      return `₾`;
    case Currency.AzerbaijaniManat:
    case CurrencyCode.AzerbaijaniManat:
      return `₼`;
    case Currency.SriLankanRupee:
    case CurrencyCode.SriLankanRupee:
      return `Rs.`;
    case Currency.SerbianDinar:
    case CurrencyCode.SerbianDinar:
      return `DIN`;
    case Currency.SaudiRiyal:
    case CurrencyCode.SaudiRiyal:
      return `SR`;
    case Currency.MongolianTugrik:
    case CurrencyCode.MongolianTugrik:
      return `₮`;
    case Currency.SouthAfricanRand:
    case CurrencyCode.SouthAfricanRand:
      return `R`;
    case Currency.IranianRial:
    case CurrencyCode.IranianRial:
      return `IR`;
    case Currency.IndonesianRupiah:
    case CurrencyCode.IndonesianRupiah:
      return `Rp`;
    case Currency.VietnameseDong:
    case CurrencyCode.VietnameseDong:
      return `đ`;
    case Currency.NewTurkmenManat:
    case CurrencyCode.NewTurkmenManat:
      return `TMT`;
    case Currency.BrazilianReal:
    case CurrencyCode.BrazilianReal:
      return `R$`;
    default:
      return null;
  }
}
